apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: stg
namePrefix: stg-
commonAnnotations:
  branch: master
commonLabels:
  app: app-nginx-stg

patches:
  - target:
      kind: Deployment
      name: nginx
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
